FIND_PACKAGE(GLEW REQUIRED)
INCLUDE_DIRECTORIES(${GLEW_INCLUDE_DIRS})
LINK_LIBRARIES(${GLEW_LIBRARIES})

IF (WIN32)
	find_package(glfw3 CONFIG REQUIRED)
	LIST(APPEND stdgl_libraries glfw ${GLEW_LIBRARIES})
ELSE ()
	FIND_PACKAGE(PkgConfig REQUIRED)
	pkg_search_module(GLFW3 REQUIRED glfw3)
	INCLUDE_DIRECTORIES(${GLFW3_INCLUDE_DIRS})
	LIST(APPEND stdgl_libraries ${GLFW3_STATIC_LIBRARIES} ${GLEW_LIBRARIES})
ENDIF ()


message(STATUS "GLEW_LIBRARIES=${GLEW_LIBRARIES}")
message(STATUS "GLFW_LIBRARIES=${GLFW3_STATIC_LIBRARIES}")
